apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "service.fullname" . }}
  labels:
{{ include  "service.labels" . | indent 4 }}
data:
  {{- tpl (toYaml .Values.configmap.data) $ | nindent 2 }}
