apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "service.fullname" . }}
  labels:
{{ include  "service.labels" . | indent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret.data | nindent 2 }}
